spring.application.name=autenticacao_google
#Spring config properties
spring.config.import=optional:file:.env[.properties]
#Autenticação, id e secret da conta google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

